### ISSUE TITLE
CORS OPTIONS pass-through

### ISSUE THREAD

**Issue by Erhannis** [silb/shiro-jersey#10]
When you send a POST request to a URL different than the one you're on, the browser first sends an OPTIONS request, without login cookies or anything.  Shiro deflects this as an unauthorized request.  I read that the correct handling is to pass OPTIONS requests without checking authorization.  How can I do that, using this library?

**Comment by silb** [comment]
You can configure Shiro to make authentication optional. See <https://github.com/silb/shiro-jersey/blob/master/src/test/resources/org/secnod/shiro/test/integration/webapp/WEB-INF/shiro.ini>.
