### ISSUE TITLE
How the login will be performed.

### ISSUE THREAD

**Issue by saikat-ganguly** [silb/shiro-jersey#7]
Hi,

I have found your library quite helpful. I want to use it in my app. My requirement is bit different though. I want to secure my rest services which will be used in both javascript client and mobile application client. So I want a common authentication point for them.I couldn't find how we would login using this library. Can you please help me how can I achieve it. My software stack trace is 
Embedded Jetty , Jersey , Guice. 

Thanks In advance

**Comment by silb** [comment]
Did you find the [blog post](http://blog.silb.no/shiro-securing-dropwizard.html) I wrote about a similar topic?

**Comment by saikat-ganguly** [comment]
Hi Stig,

Thank you very much for the reply. My requirement and configuration is a
bit different. First of all let me tell you what I understand about
BasicAuthenticationFilter aka authcBasic. If we use authcBasic then every
request will be authenticated with username/password. But that not what we
want. We are using Jersey web services running in embedded jetty and Guice
is used for Dependency Injection. So what we want to do is there will be a
custom rest service for login. User will post username/password and upon
successfully login a Bearer Token will be sent in response. From the next
time the user is going to call a protected resource it will send the Bearer
Token in Authorization Header and we will read then and authorize.

To do that I was thinking about extending AuthenticatingFilter  ,
AuthorizingRealm and AuthenticationToken. That way we could have our custom
implementation.

Can you please suggest if we are in the right track. Also am I right about
authcBasic ?

Thank you for your valuable time.

On Thu, Dec 10, 2015 at 12:59 AM, Stig Inge Lea Bjørnsen <
notifications@github.com> wrote:

> Did you find the blog post
> <http://blog.silb.no/shiro-securing-dropwizard.html> I wrote about a
> similar topic?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/silb/shiro-jersey/issues/7#issuecomment-163365647>.
>



-- 
Thanks and Regards!

*Saikat Ganguly (Senior Software Engineer) *
*LMS Solutions(India) Pvt.Ltd*

*18, Professor Colony (Wadhwani Chamber) Bhawakuan
,Indore-452001(M)+917566540651 (O)+7314289083*

**Comment by silb** [comment]
That's exactly what my blog post describes, combining preemptive HTTP basic authentication with session cookie authentication.
