### ISSUE TITLE
It seems that Filter doesn't take effect

### ISSUE THREAD

**Issue by yu2003w** [silb/shiro-jersey#9]
Hi,
My app is restful web service integrated with jersey and running on tomcat.
I tried to use shiro-jersey to enable authentication and authorization.
However, after configure [urls] in shiro.ini, it seemed it didn't take effect.
I guessed I missed something, so I asked here for help.

I found following example,
public class ApiApplication extends ResourceConfig {
    public ApiApplication() {
        register(new AuthorizationFilterFeature());
        register(new SubjectFactory());
        register(new AuthInjectionBinder());
    }
}

Where should I do the similar thing in my web app?
I tried to add the following code into the entry point for web application,
@Path("/")
@RequiresAuthentication
public class InfoCenter extends ResourceConfig {
	public InfoCenter() {
		initDataSource();
		register(new AuthorizationFilterFeature());
        register(new SubjectFactory());
        register(new AuthInjectionBinder());
        register(new ShiroExceptionMapper());	
	}

This class has some methods to handle http requests and below annotations are added to them,
@RequiresAuthentication
 @RequiresPermissions("list:view")
And the shiro.ini is as below,
/services/info/list/student/* = authc, roles[admin]
/services/info/add/** = authc, roles[admin]
/services/info/update/** = authc, roles[admin]
/services/info/delete/** = authc, roles[admin]

However, it didn't work. 
Could you help to have a look?

Thanks.

**Comment by silb** [comment]
Maybe you forgot the Shiro filter in web.xml?

If you have trouble getting Shiro to work with JAX-RS, try to get it to work without JAX-RS first by following the documentation from the Shiro project.
